name: eugene
favicon: null
layout_spectrum: 0.964943636674434
typography_spectrum: 0.3983536818996072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2445492900442332
  lightness: 0.5421312260441482
  saturation: 0.40083434199914336
  rhythmicContrast: 0.5749478014186025
purpose: []
